"""add user DNI and state

Revision ID: 5c87bc186c63
Revises: 007e5ce8fc01
Create Date: 2026-04-14 13:35:33.352965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c87bc186c63'
down_revision: Union[str, Sequence[str], None] = '007e5ce8fc01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Definir el enum UNA sola vez
user_state_enum = sa.Enum('ACTIVE', 'PENDING', name='userstate')


def upgrade() -> None:
    """Upgrade schema."""
    
    # Crear el tipo ENUM en la DB
    user_state_enum.create(op.get_bind())

    # Agregar columnas
    op.add_column('users', sa.Column('DNI', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('state', user_state_enum, nullable=True))  # ⚠️ nullable=True por ahora

    # Ajustes existentes
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    op.create_unique_constraint(None, 'users', ['DNI'])

    # setear valor por defecto si ya hay datos
    op.execute("UPDATE users SET state = 'PENDING'")

    # Ahora sí lo haces NOT NULL
    op.alter_column('users', 'state', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'state')
    op.drop_column('users', 'DNI')
    # ### end Alembic commands ###
