"""setup_inicial

Revision ID: 92b5b1b6b42e
Revises: 84cb7e325a95
Create Date: 2026-04-14 11:22:19.622389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b5b1b6b42e'
down_revision: Union[str, Sequence[str], None] = '84cb7e325a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('patients_doctor_id_fkey'), 'patients', type_='foreignkey')
    op.drop_column('patients', 'doctor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('patients_doctor_id_fkey'), 'patients', 'doctors', ['doctor_id'], ['id'])
    # ### end Alembic commands ###
