"""make_email_and_password_nullable

Revision ID: a93c201baade
Revises: 147db905e2b0
Create Date: 2026-04-19 22:44:29.601634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a93c201baade'
down_revision: Union[str, Sequence[str], None] = '147db905e2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'birthdate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='usergender'),
               nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_constraint(op.f('users_DNI_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_DNI'), 'users', ['DNI'], unique=True)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_DNI'), table_name='users')
    op.create_unique_constraint(op.f('users_DNI_key'), 'users', ['DNI'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='usergender'),
               nullable=False)
    op.alter_column('users', 'birthdate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
